task:
  name: G1Walk
  env: isaaclab.tasks.g1_walk.g1_task.G1WalkEnv
  cfg: isaaclab.tasks.g1_walk.g1_cfg.G1_CFG
  episode_length: 500
  reward_scale: 1.0

train:
  algorithm: ppo
  learning_rate: 0.0003
  batch_size: 256
  num_steps: 1_000_000  # number of training steps
  eval_interval: 10_000  # evaluate every 10k steps
  eval_episodes: 5

log:
  log_dir: logs/g1_walk
  save_interval: 50_000
